name: Redis Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker build .
        docker run -d -p 6379:6379 redis
